env: 'local'
timeout:
  shutdownSeconds: 30
http:
  host: '127.0.0.1'
  port: 8080
logger:
  level: 'http' # Log only if less than or equal to this level
  format: 'text'
database:
  host: '127.0.0.1'
  port: 5435
  user: 'mrc-client'
  password: 'Client123!'
redis:
  host: '127.0.0.1'
  port: 6381
  password: 'mrcRedis'
jwt:
  expirationHour: 720
  activeKeyPair: v1
  keyPairs:
    - name: v1
      private: <private_key>
      public: <public_key>
google:
  oauth:
    clientId: <client_id>
    clientSecret: <client_secret>
    redirectPath: /api/v1/google/sign-in/token
  endpoints:
    auth: https://accounts.google.com/o/oauth2/auth
    token: https://oauth2.googleapis.com/token
oauth:
  stateExpirationMinutes: 10

